######################################################################
# Automatically generated by qmake (2.01a) lun feb 4 19:45:18 2013
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = image-resize
TEMPLATE = app


SOURCES += main.cpp

HEADERS +=

FORMS   +=
